name: builds

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-windows-2022:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        target:
          - raddbg
          - radlink
          - rdi_from_pdb
          - raddump
          - rdi_breakpad_from_pdb
        compiler: [msvc]
        mode: [release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build (VS 2022, MSVC Release)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call build ${{ matrix.target }} ${{ matrix.compiler }} ${{ matrix.mode }} || exit /b 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.compiler }}-${{ matrix.mode }}
          path: |
            build\${{ matrix.target }}\${{ matrix.compiler }}\${{ matrix.mode }}\*.exe
